default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: url_shortner_development

test:
  <<: *default
  database: url_shortner_test

production:
  <<: *default
  database: url_shortner_production
  username: url_shortner
  password: <%= ENV['FLUID_CONTACT_DATABASE_PASSWORD'] %>

